FROM node:22.14.0-slim

EXPOSE 3000

WORKDIR /app

COPY ./package*.json ./

RUN npm ci

COPY . .

ARG BACKEND_HOST
ARG FRONTEND_HOST
ARG PORT
ARG MONGO_URI
ARG REDIS_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG SESSION_SECRET
ARG AWS_BUCKET_NAME
ARG AWS_BUCKET_REGION
ARG AWS_BUCKET_ACCESS_KEY
ARG AWS_BUCKET_SECRET_KEY

ENV BACKEND_HOST=$BACKEND_HOST
ENV FRONTEND_HOST=$FRONTEND_HOST
ENV PORT=$PORT
ENV MONGO_URI=$MONGO_URI
ENV REDIS_URL=$REDIS_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV SESSION_SECRET=$SESSION_SECRET
ENV AWS_BUCKET_NAME=$AWS_BUCKET_NAME
ENV AWS_BUCKET_REGION=$AWS_BUCKET_REGION
ENV AWS_BUCKET_ACCESS_KEY=$AWS_BUCKET_ACCESS_KEY
ENV AWS_BUCKET_SECRET_KEY=$AWS_BUCKET_SECRET_KEY

CMD ["npm", "run", "dev"]
